### ISSUE TITLE
Strange panic on track.len()

### ISSUE THREAD

**Issue by anton-okolelov** [nicklan/rimd#1]
I tried to create a simple midi file with a note on message. But I have panic

```
extern crate rimd;

use rimd::{MidiMessage,SMFBuilder,SMFWriter,TrackEvent,Event};
use std::path::Path;

fn main() {

    let note_on = MidiMessage::note_on(1,1,0);
    let note_off = MidiMessage::note_off(1,1,0);


    let mut builder = SMFBuilder::new();
    builder.add_track();

    println!("{}", builder.num_tracks());
    let ev = Event::Midi(note_on);
    let event = TrackEvent{vtime: 5, event: ev};
    builder.add_event(1, event);
    let smf = builder.result();

   let writer = SMFWriter::from_smf(smf);
   let result = writer.write_to_file(Path::new("/home/user/file.smf"));

}

```

The result is 
thread '<main>' panicked at 'assertion failed: self.tracks.len() < track', /home/user/.cargo/git/checkouts/rimd-a7d4e2e6ea4a3a00/master/src/builder.rs:334
An unknown error occurred

I don't understand. I've added a track by "builder.add_track"

**Comment by nicklan** [comment]
I think this was from the assertion bug you fixed.  If so, can you close this?  Thanks for the report and the fix!
